services:
  - type: web
    name: dicti-backend
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y hunspell libhunspell-dev
      pip install -r requirements.txt
    startCommand: gunicorn app:app
